import random
wlcm_msg="""

______           _       ______                       _____      _                        
| ___ \         | |      | ___ \                     /  ___|    (_)                       
| |_/ /___   ___| | __   | |_/ /_ _ _ __   ___ _ __  \ `--.  ___ _ ___ ___  ___  _ __ ___ 
|    // _ \ / __| |/ /   |  __/ _` | '_ \ / _ \ '__|  `--. \/ __| / __/ __|/ _ \| '__/ __|
| |\ \ (_) | (__|   < _  | | | (_| | |_) |  __/ |_   /\__/ / (__| \__ \__ \ (_) | |  \__ \ 
\_| \_\___/ \___|_|\_( ) \_|  \__,_| .__/ \___|_( )  \____/ \___|_|___/___/\___/|_|  |___/
                     |/            | |          |/                                        
                                   |_|                                                    


Copyright © 2022 Florian LAVIE
This program is released under license GPL-3.0-or-later

This program is part of a project called "Python Learning Projects"
Source code & license available at https://github.com/flolavie/python-learning-projects/
Author's contact: contact@flolavie.fr - www.flolavie.fr


Credits & Thanks
  ♥ My mom and friends, they're awesome ♥
  ♥ Fancy text generated by 'Text ASCII Art Generator' from https://patorjk.com/

"""
print(wlcm_msg)

#=======================
#Language selection part
#=======================
def select_language():
    print("Please, select your language :\n- English : Type 'en'\n- Français : Tapez 'fr'")

    language = input("Language -> ")

    if language == "fr":
        print("\n✔ Vous avez sélectionné le Français.\n")
        play_fr()
    elif language == "en":
        print("\n✔ You selected English\n")
        play_en()
    else:
        print("\n/!\ Error, language not available. /!\ \n")
        select_language()


#============
# Game part
#============

# ENGLISH
def play_en():
    item_list = ["Rock", "Paper", "Scissors"]
    bot_choice = random.randint(0,2)
    print("Choose your next move!")
    selected_item = input("Rock / Paper / Scissors -> ")
    win_msg = "\nThe {} beats the {}, congratulations you won!\n"
    lose_msg = "\nSadly, the {} beats the {}, you lost...\n"
    noob_msg = "\nWell, you both choose {}, let's play again!\n"

    def fail():
        print(noob_msg.format(selected_item))
        play_en()
    
    match bot_choice:
        case 0:
            print(win_msg.format(selected_item,item_list[bot_choice])) if selected_item == item_list[1] else print(lose_msg.format(item_list[bot_choice],selected_item)) if selected_item == item_list[2] else fail()
        case 1:
            print(win_msg.format(selected_item,item_list[bot_choice])) if selected_item == item_list[2] else print(lose_msg.format(item_list[bot_choice],selected_item)) if selected_item == item_list[0] else fail()
        case 2:
            print(win_msg.format(selected_item,item_list[bot_choice])) if selected_item == item_list[0] else print(lose_msg.format(item_list[bot_choice],selected_item)) if selected_item == item_list[1] else fail()


# FRENCH
def play_fr():
    item_list = ["Pierre", "Feuille", "Ciseaux"]
    bot_choice = random.randint(0,2)
    print("Choisis ton prochain geste !")
    selected_item = input("Pierre / Feuille / Ciseaux -> ")
    win_msg = "\n{} bat {}, félicitations vous avez gagné !\n"
    lose_msg = "\nMalheureusement, {} bat {}, vous avez perdu...\n"
    noob_msg = "\nAïe, vous avez tous les deux choisis {}, retentez votre chance !\n"

    def fail():
        print(noob_msg.format(selected_item))
        play_fr()
    
    match bot_choice:
        case 0:
            print(win_msg.format(selected_item,item_list[bot_choice])) if selected_item == item_list[1] else print(lose_msg.format(item_list[bot_choice],selected_item)) if selected_item == item_list[2] else fail()
        case 1:
            print(win_msg.format(selected_item,item_list[bot_choice])) if selected_item == item_list[2] else print(lose_msg.format(item_list[bot_choice],selected_item)) if selected_item == item_list[0] else fail()
        case 2:
            print(win_msg.format(selected_item,item_list[bot_choice])) if selected_item == item_list[0] else print(lose_msg.format(item_list[bot_choice],selected_item)) if selected_item == item_list[1] else fail()


select_language()